# Generated by Django 5.1.15 on 2026-10-04 14:25

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='diprun',
            constraint=models.UniqueConstraint(core.models.LocalDipDate(models.F('started_at')), models.F('roll'), name='uniq_one_dip_per_roll_per_day'),
        ),
    ]
